# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/italian',
                'doc_host': 'https://AndrewBoney.github.io',
                'git_url': 'https://github.com/AndrewBoney/italian',
                'lib_path': 'italian'},
  'syms': {'italian.core': {'italian.core.foo': ('core.html#foo', 'italian/core.py')}}}