# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_lesson.ipynb.

# %% auto 0
__all__ = ['save_text_mp3', 'say_mp3']

# %% ../00_lesson.ipynb 3
from fastcore.test import *

# %% ../00_lesson.ipynb 6
import gtts
from playsound import playsound

def save_text_mp3(text: str, loc: str, lang: str = "it"):
    tts = gtts.gTTS(text, lang = "it")
    tts.save(loc)
    
def say_mp3(loc: str):
    playsound(loc)
